FROM node:11.9.0-slim

#RUN apt upgrade -y && apt update -y

RUN apt-get update && apt-get install vim -y && apt-get install libcurl3 \
    mkdir -p /usr/local/MATLAB/MATLAB_Runtime && \
    mkdir -p  /usr/lib/x86_64-linux-gnu

COPY v95 /usr/local/MATLAB/MATLAB_Runtime/v95

#COPY x86_64-linux-gnu /usr/lib/x86_64-linux-gnu

WORKDIR /rxds/node/runner

COPY ["appconfig_master.js","appconfig_tesla.js","instance.sh","instance_new.sh","node_modules","package-lock.json", "spot.sh", "typed.js", "appconfig_k8.js", "assert.js", "instance.json", "libc.js", "package.json", "run_k8.js", "t.js", "wsq.js", "./"]

RUN npm install

CMD ["node", "run_k8.js"]

